### ISSUE TITLE
FATAL EXCEPTION: pool-2-thread-1

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo#44] opened 2019-05-18 17:30 UTC
I updated Flutter, Dart and Android Studio and now when I try to open the picker, the app crashes reporting only this error:

```
E/AndroidRuntime( 6350): FATAL EXCEPTION: pool-2-thread-1
E/AndroidRuntime( 6350): Process: boydpearce.my_grand_kids, PID: 6350
E/AndroidRuntime( 6350): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-2-thread-1
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime( 6350): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:131)
E/AndroidRuntime( 6350): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime( 6350): 	at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:553)
E/AndroidRuntime( 6350): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6350): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6350): 	at java.lang.Thread.run(Thread.java:764)
I/Process ( 6350): Sending signal. PID: 6350 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"15","method":"getVM","params":{}}
```

I'm using:
    Dart 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)
    Flutter 1.6.0
    Android Studio (version 3.4.1)

Plugins:
  photo: 0.3.3
  sqflite: 1.1.5
  path_provider: 0.5.0+1
  cached_network_image: ^0.8.0
  curved_navigation_bar: ^0.1.26
  image_picker: ^0.6.0+3
  fluttertoast: ^3.0.3
  photo_view: ^0.3.3
  esys_flutter_share: ^1.0.0
  uuid: 2.0.0
  image_downloader: ^0.15.2
  image: ^2.0.7
  intl: ^0.15.8

I'm pretty sure it is a version incompability bug because I'm versioning my code and now also old version of my project don't work.
How can I fix it?

**Comment by rignaneseleo** [comment] 2019-05-18 18:23
UPDATE: downgrading Flutter from 1.6.0 to 1.5.8 solved the problem.

Is there a bug in Flutter 1.6.0 or an incompatibilty of this plugin with it?

**Comment by CaiJingLong** [comment] 2019-05-19 02:23
As you can find, this error is caused by the same reason as flutter/flutter#32315.
I will refer to image_picker to fix this problem.

**Comment by CaiJingLong** [comment] 2019-05-19 10:00
I fix it in https://github.com/CaiJingLong/flutter_photo_manager/commit/fd6d444db48301c236aa6395e0f847b69c5ab4d7

Update version to 0.3.4 and retry.

**Comment by CaiJingLong** [comment] 2019-05-21 00:52
I'm closing this issue. 
If you has problem, please reopen it.

**Closed by CaiJingLong** 2019-05-21 00:52 UTC
